import { expect, test, type Page } from "@playwright/test";

import { mockApi, setTheme, signedInSession, sseBody, trackConsoleErrors } from "../helpers";
import { atlasTreePayload, summaryMock } from "../graph/fixtures";
import { emptyReply, graphMocks, SESSION_ID } from "./fixtures";

/*
 * Dr. Wu's symptom-overlap ranking (`reply.symptom_match`): a card with the conditions in
 * order, the shared symptoms, an overlap count and the "not a diagnosis" line, the same from a
 * live stream, a stored reply and a replayed run, on the full chat page and in the Atlas dock.
 */

const MESSAGE_ID = "22222222-2222-4222-8222-222222222222";
const RUN_ID = "44444444-4444-4444-8444-444444444444";
const NOTE = "Symptom overlap in the atlas data, not a diagnosis.";

// Fixture graph (apps/backend/src/backend/fixtures/demo_graph.json): both diseases are on the
// map in the mocked tree; the third id is not in the tree and has no node mock.
const SEIZURES = "My son has seizures, low muscle tone and a developmental delay. No feeding problems.";
const OFF_MAP = "MONDO:0000001";
const term = (user_symptom: string, edge_id: string, recorded_as = user_symptom, match = "same") => ({ user_symptom, recorded_as, match, edge_id });
const seizureMatch = {
  items: [
    {
      id: "MONDO:9900007",
      label: "STXBP1 encephalopathy",
      overlap: 3,
      of: 3,
      on_map: true,
      shared: [term("Seizure", "e_bbb03f09d0fa"), term("Global developmental delay", "e_212b5611fc6d"), term("Hypotonia", "e_2102fff024d0")],
      absent: [term("Feeding difficulties", "e_73bd184c2a04")],
    },
    {
      id: "MONDO:9900006",
      label: "SCN8A developmental and epileptic encephalopathy",
      overlap: 3,
      of: 3,
      on_map: true,
      shared: [term("Seizure", "e_d3a450dc59a6"), term("Global developmental delay", "e_73139536b382"), term("Hypotonia", "e_ae186d9b8a46")],
      absent: [],
    },
    {
      id: OFF_MAP,
      label: "Example condition not on the map",
      overlap: 1,
      of: 3,
      on_map: false,
      shared: [term("Seizure", "e_offmap_seizure", "Generalized seizure", "more_specific")],
      absent: [],
    },
  ],
};
const seizureReply = {
  ...emptyReply(
    "Some conditions in the atlas have recorded symptoms that overlap with yours. These are groups to talk over with a genetics doctor. This is not a diagnosis.",
  ),
  chips: [
    { type: "symptom", id: "HP:0001250", label: "Seizure", negated: false, confirmed: false },
    { type: "symptom", id: "HP:0011968", label: "Feeding difficulties", negated: true, confirmed: false },
  ],
  claims: [
    {
      text: "3 of your 3 symptoms are recorded for STXBP1 encephalopathy.",
      edge_ids: ["e_bbb03f09d0fa", "e_212b5611fc6d", "e_2102fff024d0"],
      origin: "observed",
      confidence: "high",
    },
  ],
  graph_focus: { node_ids: ["HP:0001250"], highlight_path: [] },
  ai_notice: "Generated by an AI system.",
  gap_search: null,
  kind: "answer",
  profile_hints: null,
  symptom_match: seizureMatch,
};

// The chronic cough ranking as the dev data gives it (2026-10-04): seven conditions record
// HP:0034315, none of them on the map; the reply keeps the top five.
const COUGH = "My son has had a chronic cough for months that never goes away. Which rare conditions have this symptom?";
const coughRows: Array<[string, string, string]> = [
  ["MONDO:0859353", "ciliary dyskinesia, primary, 49, without situs inversus", "e_c3eb574d7286"],
  ["MONDO:0054696", "immunodeficiency 53", "e_4b21893b68b5"],
  ["MONDO:0859370", "respiratory infections, recurrent, and failure to thrive with or without diarrhea", "e_dbb2ead5939a"],
  ["MONDO:0014203", "primary ciliary dyskinesia 25", "e_16f386d58183"],
  ["MONDO:0010220", "Young syndrome", "e_c8bacbea9e29"],
];
const coughMatch = {
  items: coughRows.map(([id, label, edge]) => ({
    id,
    label,
    overlap: 1,
    of: 1,
    on_map: false,
    shared:
      id === "MONDO:0859370"
        ? [term("Chronic cough", edge), term("Chronic cough", "e_cough_broader", "Cough", "broader")]
        : [term("Chronic cough", edge)],
    absent: [],
  })),
};
const coughReply = {
  ...emptyReply(
    "Seven conditions in the atlas record a chronic cough; three are types of primary ciliary dyskinesia. These are groups to talk over with a genetics doctor. This is not a diagnosis.",
  ),
  chips: [{ type: "symptom", id: "HP:0034315", label: "Chronic cough", negated: false, confirmed: false }],
  claims: [
    {
      text: "Chronic cough is recorded for primary ciliary dyskinesia 25.",
      edge_ids: ["e_16f386d58183"],
      origin: "observed",
      confidence: "high",
    },
  ],
  graph_focus: { node_ids: ["HP:0034315"], highlight_path: [] },
  ai_notice: "Generated by an AI system.",
  gap_search: null,
  kind: "answer",
  profile_hints: null,
  symptom_match: coughMatch,
};

/** Evidence for the made-up and the real-data edge ids (the fixture graph answers the rest). */
function syntheticEdge(id: string) {
  const row = coughRows.find(([, , e]) => e === id);
  const source = row ? { id: row[0], type: "disease", label: row[1] } : { id: OFF_MAP, type: "disease", label: "Example condition not on the map" };
  const target = id === "e_cough_broader" ? { id: "HP:0012735", label: "Cough" } : row ? { id: "HP:0034315", label: "Chronic cough" } : { id: "HP:0002197", label: "Generalized seizure" };
  return {
    edge: {
      id,
      source_id: source.id,
      target_id: target.id,
      relation: "has_phenotype",
      family: "symptoms",
      confidence: 0.9,
      confidence_level: "high",
      origin: "observed",
      status: "active",
      features: null,
      data_version: "test",
      evidence_count: 1,
      contradiction_count: 0,
      flagged: false,
      explanation: null,
    },
    source: { ...source, attrs: { tier: "core" } },
    target: { ...target, type: "phenotype", attrs: {} },
    supporting: [
      { id: 1, edge_id: id, tier: "curated_db", tier_weight: 0.9, source_type: "HPO", source_id: "HPO annotation", url: null, quote: null, retrieved_at: "2026-10-04T00:00:00Z", polarity: "supports", claim_type: null },
    ],
    contradicting: [],
    confidence_breakdown: { score: 0.9, terms: [] },
  };
}

const edgeMock = (req: { url: string }) => {
  const id = decodeURIComponent(new URL(req.url).pathname.split("/")[2]);
  if (id.startsWith("e_offmap") || id === "e_cough_broader" || coughRows.some(([, , e]) => e === id)) return { json: syntheticEdge(id) };
  return (graphMocks["GET /edge/*/evidence"] as (r: { url: string }) => unknown)(req);
};

const finalEvents = (reply: Record<string, unknown>) => [
  { type: "status", tool: "extract_entities", message: "Reading your message" },
  { type: "status", tool: "resolve_to_ids", message: "Matching terms to the atlas" },
  { type: "status", tool: "match_phenotypes", message: "Comparing symptoms across the atlas" },
  { type: "summary_delta", text: reply.summary },
  { type: "chips", chips: reply.chips },
  { type: "claims", claims: reply.claims, contradictions: [] },
  { type: "cards", cards: [] },
  { type: "actions", actions: [] },
  { type: "final", reply, session_id: SESSION_ID, message_id: MESSAGE_ID },
];

const session = { id: SESSION_ID, title: "Symptoms", created_at: "2026-10-04T08:00:00Z", updated_at: "2026-10-04T08:00:30Z" };
const stored = (question: string, reply: Record<string, unknown>) => ({
  session,
  messages: [
    { id: MESSAGE_ID, session_id: SESSION_ID, role: "user", content: question, reply: null, error: null, created_at: "2026-10-04T08:00:00Z" },
    { id: "55555555-5555-4555-8555-555555555555", session_id: SESSION_ID, role: "assistant", content: reply.summary, reply, error: null, created_at: "2026-10-04T08:00:30Z" },
  ],
  run: null,
});

async function server(page: Page, reply: Record<string, unknown>, extra: Record<string, unknown> = {}) {
  const nodeRequests: string[] = [];
  await mockApi(page, {
    "GET /auth/session": signedInSession({ consents: ["health_data"] }),
    "GET /chat/sessions": [],
    "GET /chat/runs": [],
    "GET /profile": { updated_at: "2026-10-03T00:00:00Z" },
    "GET /atlas/tree.json": atlasTreePayload(),
    "GET /atlas/summary/*": summaryMock(),
    ...graphMocks,
    "GET /node/*": (req: { url: string }) => {
      nodeRequests.push(decodeURIComponent(new URL(req.url).pathname.split("/")[2]));
      return (graphMocks["GET /node/*"] as (r: { url: string }) => unknown)(req);
    },
    "GET /edge/*/evidence": edgeMock,
    "POST /chat": () => sseBody(finalEvents(reply)),
    ...extra,
  });
  return { nodeRequests };
}

async function ask(page: Page, text: string) {
  const box = page.getByRole("textbox", { name: "Message Dr. Wu" });
  await box.fill(text);
  await box.press("Enter");
}

const card = (scope: Page | ReturnType<Page["getByTestId"]>) => scope.getByTestId("card-symptom_match");

async function expectSeizureCard(c: ReturnType<Page["getByTestId"]>) {
  await expect(c).toBeVisible();
  await expect(c.getByTestId("symptom-match-note")).toHaveText(NOTE);
  const items = c.getByTestId("symptom-match-item");
  await expect(items).toHaveCount(3);
  await expect(items.nth(0)).toHaveAttribute("data-node-id", "MONDO:9900007");
  await expect(items.nth(1)).toHaveAttribute("data-node-id", "MONDO:9900006");
  await expect(items.nth(0).getByTestId("symptom-match-overlap")).toHaveText("3 of your 3 symptoms:");
  await expect(items.nth(0).getByTestId("symptom-match-shared")).toHaveText(["Seizure", "Global developmental delay", "Hypotonia"]);
  await expect(items.nth(0).getByTestId("symptom-match-absent")).toContainText("Feeding difficulties");
  await expect(items.nth(2).getByTestId("symptom-match-shared")).toContainText("Generalized seizure· narrower term");
  await expect(items.nth(2).getByTestId("atlas-offmap")).toBeVisible();
  await expect(items.nth(0).getByTestId("atlas-offmap")).toHaveCount(0);
  // An overlap count only: nothing that reads as a probability.
  expect(await c.innerText()).not.toMatch(/%|probab|likel|chance/i);
}

test.describe("Dr. Wu symptom ranking", () => {
  test("full page: the card from the live stream, with links and cited sources", async ({ page }) => {
    await server(page, seizureReply);
    const errors = trackConsoleErrors(page);
    await page.goto("/chat");
    await ask(page, SEIZURES);
    const turn = page.getByTestId("assistant-turn").last();
    await expect(turn).toHaveAttribute("data-phase", "done");
    const c = card(turn);
    await expectSeizureCard(c);
    const items = c.getByTestId("symptom-match-item");
    // On the map: the Atlas in memory (no id in the URL); not on the map: its node page.
    await expect(items.nth(0).getByTestId("symptom-match-link")).toHaveAttribute("href", "/atlas");
    await expect(items.nth(2).getByTestId("symptom-match-link")).toHaveAttribute("href", `/node/${encodeURIComponent(OFF_MAP)}`);
    // Every shown symptom is backed by its has_phenotype link.
    await items.nth(0).getByRole("button", { name: "Sources · 4 links" }).click();
    await expect(items.nth(0).getByTestId("edge-item")).toHaveCount(4);
    await expect(items.nth(0).locator('[data-edge-id="e_73bd184c2a04"]')).toContainText("Feeding difficulties");
    // The card sits before the claims.
    const before = await turn.evaluate((el) => {
      const all = Array.from(el.querySelectorAll("*"));
      return all.indexOf(el.querySelector('[data-testid="card-symptom_match"]')!) < all.indexOf(el.querySelector('[data-testid="claim"]')!);
    });
    expect(before).toBe(true);
    expect(errors()).toEqual([]);
  });

  test("full page: a stored reply renders the same card", async ({ page }) => {
    await server(page, seizureReply);
    await page.goto("/chat");
    await ask(page, SEIZURES);
    await expect(page.getByTestId("assistant-turn").last()).toHaveAttribute("data-phase", "done");
    const live = await card(page).innerText();

    await server(page, seizureReply, { "GET /chat/sessions": [session], "GET /chat/sessions/*": stored(SEIZURES, seizureReply) });
    await page.goto("/chat");
    await page.getByTestId("session-list").first().getByRole("button", { name: /^Symptoms/ }).click();
    const c = card(page.getByTestId("assistant-turn").last());
    await expectSeizureCard(c);
    expect(await c.innerText()).toBe(live);
  });

  test("full page: replies stored before the ranking show no card", async ({ page }) => {
    const old = { ...seizureReply } as Record<string, unknown>;
    delete old.symptom_match;
    await server(page, old, { "GET /chat/sessions": [session], "GET /chat/sessions/*": stored(SEIZURES, old) });
    await page.goto("/chat");
    await page.getByTestId("session-list").first().getByRole("button", { name: /^Symptoms/ }).click();
    const turn = page.getByTestId("assistant-turn").last();
    await expect(turn.getByTestId("summary")).toBeVisible();
    await expect(card(turn)).toHaveCount(0);
    await expect(turn.getByTestId("claim")).toHaveCount(1);
  });

  test("dock: the live card selects conditions on the map and lists the finds by name", async ({ page }) => {
    const { nodeRequests } = await server(page, seizureReply);
    const errors = trackConsoleErrors(page);
    await page.goto("/atlas");
    const dock = page.getByTestId("atlas-wu-dock");
    await dock.getByTestId("atlas-wu-open").click();
    await ask(page, SEIZURES);
    await expect(dock.getByTestId("atlas-wu-turn")).toHaveAttribute("data-phase", "done");
    const c = card(dock);
    await expectSeizureCard(c);
    const items = c.getByTestId("symptom-match-item");
    await expect(items.nth(2).getByTestId("symptom-match-link")).toHaveAttribute("href", `/node/${encodeURIComponent(OFF_MAP)}`);
    // The finds list carries the ranked conditions, the one off the map by the reply's name.
    const found = dock.getByTestId("atlas-wu-found-item");
    await expect(found.filter({ hasText: "Example condition not on the map" })).toHaveAttribute("data-offmap", "true");
    await expect(found.filter({ hasText: "STXBP1 encephalopathy" })).toHaveCount(1);
    expect(nodeRequests).not.toContain(OFF_MAP);
    // On the map: selecting opens its summary in the panel, no id in the URL.
    await items.nth(0).getByTestId("symptom-match-link").click();
    await expect(page.getByTestId("atlas-panel")).toContainText("STXBP1 encephalopathy");
    expect(page.url()).not.toContain("MONDO");
    expect(errors()).toEqual([]);
  });

  test("dock: a run replayed after a reload shows the same card", async ({ page }) => {
    const run = { id: RUN_ID, session_id: SESSION_ID, message_id: MESSAGE_ID, created_at: "2026-10-04T08:00:00Z" };
    let finished = false;
    const events = [{ type: "turn", session_id: SESSION_ID, message_id: MESSAGE_ID, run_id: RUN_ID }, ...finalEvents(seizureReply)];
    await server(page, seizureReply, {
      "GET /chat/sessions": [session],
      "GET /chat/runs": () => ({ json: finished ? [] : [run] }),
      "GET /chat/sessions/*": () => ({
        json: finished ? stored(SEIZURES, seizureReply) : { ...stored(SEIZURES, seizureReply), messages: stored(SEIZURES, seizureReply).messages.slice(0, 1), run },
      }),
      [`GET /chat/runs/${RUN_ID}/events`]: () => {
        finished = true;
        return { contentType: "text/event-stream", body: events.map((e, i) => `id: ${i + 1}\nevent: ${e.type}\ndata: ${JSON.stringify(e)}\n\n`).join("") };
      },
    });
    await page.goto("/atlas");
    const dock = page.getByTestId("atlas-wu-dock");
    await expect(dock.getByTestId("atlas-wu-turn")).toHaveAttribute("data-phase", "done");
    await expectSeizureCard(card(dock));
  });

  test("full page and dock with the chronic cough ranking, screenshots", async ({ page }) => {
    const dir = process.env.WU_SHOTS;
    test.skip(!dir, "set WU_SHOTS to a folder to write the screenshots");
    await setTheme(page, "light");
    for (const width of [1440, 390]) {
      await page.setViewportSize({ width, height: width > 500 ? 900 : 844 });
      await server(page, coughReply);
      await page.goto("/chat");
      await ask(page, COUGH);
      const turn = page.getByTestId("assistant-turn").last();
      await expect(turn).toHaveAttribute("data-phase", "done");
      const c = card(turn);
      await expect(c.getByTestId("symptom-match-item")).toHaveCount(5);
      await expect(c.getByTestId("symptom-match-item").nth(2).getByTestId("symptom-match-shared")).toHaveText(["Chronic cough", "Cough· broader term"]);
      await c.scrollIntoViewIfNeeded();
      await c.screenshot({ path: `${dir}/wu-ranking-page-${width}.png`, animations: "disabled" });
      await page.screenshot({ path: `${dir}/wu-ranking-page-${width}-view.png`, animations: "disabled" });

      await page.goto("/atlas");
      const dock = page.getByTestId("atlas-wu-dock");
      await dock.getByTestId("atlas-wu-open").click();
      await ask(page, COUGH);
      await expect(page.getByTestId("atlas-wu-turn")).toHaveAttribute("data-phase", "done");
      const dc = card(page.getByTestId("atlas-wu-body"));
      await expect(dc.getByTestId("symptom-match-item")).toHaveCount(5);
      await dc.scrollIntoViewIfNeeded();
      await page.screenshot({ path: `${dir}/wu-ranking-dock-${width}.png`, animations: "disabled" });
    }
  });
});
