/**
 * Live signed-in path features: an uncached explanation generated by the
 * model (mock OpenAI), proposal export, and gap search over SSE from a pair
 * with no supported route (candidates stay pending review).
 * Start the processes as described in live-helpers.ts, then `PORT=3106 pnpm test:e2e:live`.
 */
import { expect, test } from "@playwright/test";

import { deleteAccount, passWelcome, resetMock, shot, signInAs, trackProblems } from "./live-helpers";

// DEE4 → Dravet syndrome: supported, but no precomputed explanation.
const UNCACHED = "/path?from=MONDO%3A0012812&to=MONDO%3A0100135";
const NO_ROUTE = "/path?from=MONDO%3A0012812&to=MONDO%3A0011297&family=dna";

test.describe("signed-in path features", () => {
  test.beforeEach(async ({ request }) => resetMock(request));

  test("uncached explanation, proposal export and gap search", async ({ page, context }) => {
    await signInAs(page, "carol");
    await deleteAccount(page);
    await page.context().clearCookies();
    await signInAs(page, "carol", UNCACHED);
    await expect(page).toHaveURL(/\/welcome/);
    await page.getByTestId("chatgpt-plan-notice").getByRole("button", { name: "Got it" }).click();
    await passWelcome(page);
    const problems = trackProblems(page);
    try {
      // Sign-in returns to the path only, never the query string (by design).
      await expect(page).toHaveURL(/\/path$/);
      await page.goto(UNCACHED);
      const explanation = page.getByTestId("explanation");
      // Generated on the first run, then served from explanations_cache (keyed
      // by path, role, language and data version) on every later run.
      await expect(explanation.getByTestId("explanation-fresh").or(explanation.getByTestId("explanation-cached"))).toBeVisible({
        timeout: 60_000,
      });
      await expect(explanation.getByTestId("explanation-text")).not.toBeEmpty();
      await expect(explanation.getByTestId("explanation-text")).not.toContainText("[e_");
      await shot(page, "path-fresh-explanation");

      const [popup] = await Promise.all([context.waitForEvent("page"), page.getByTestId("export-proposal").click()]);
      await expect(popup.locator("body")).toContainText("Who is connected and why");
      await expect(popup.locator("body")).toContainText(/Sources: /);
      await expect(popup.locator("body")).toContainText("Not medical advice");
      await popup.close();

      await page.goto(NO_ROUTE);
      await expect(page.getByTestId("coverage-report")).toBeVisible({ timeout: 30_000 });
      await page.getByTestId("gap-start").click();
      const gap = page.getByTestId("gap-search");
      await expect(gap.getByTestId("ai-disclosure")).toBeVisible();
      await expect(page.getByTestId("gap-progress")).not.toBeEmpty();
      await expect(page.getByTestId("gap-ending")).toBeVisible({ timeout: 120_000 });
      const candidates = page.getByTestId("gap-candidate");
      for (let i = 0; i < (await candidates.count()); i++) {
        await expect(candidates.nth(i).getByTestId("pending-review-label")).toBeVisible();
      }
      await shot(page, "path-gap-search", { fullPage: true });
      expect(problems()).toEqual([]);
    } finally {
      await deleteAccount(page);
    }
  });
});
